// glossary.ts — PM Interview Glossary Data
// Design: PM War Room — dark navy, indigo accent

export type GlossaryCategory =
  | "Engagement Metrics"
  | "Growth & Acquisition"
  | "Revenue & Business"
  | "Quality & Satisfaction"
  | "Product Frameworks"
  | "Experimentation"
  | "Infrastructure & Tech";

export interface GlossaryTerm {
  id: string;
  term: string;
  fullName: string;
  category: GlossaryCategory;
  definition: string;
  formula?: string;
  example?: string;
  relatedTerms?: string[];
  usedIn?: string[]; // which question types this comes up in
}

export const CATEGORY_COLORS: Record<GlossaryCategory, string> = {
  "Engagement Metrics":    "#6366f1", // indigo
  "Growth & Acquisition":  "#10b981", // emerald
  "Revenue & Business":    "#f59e0b", // amber
  "Quality & Satisfaction":"#ec4899", // pink
  "Product Frameworks":    "#8b5cf6", // violet
  "Experimentation":       "#06b6d4", // cyan
  "Infrastructure & Tech": "#64748b", // slate
};

export const glossary: GlossaryTerm[] = [
  // ── Engagement Metrics ──────────────────────────────────────────────
  {
    id: "dau",
    term: "DAU",
    fullName: "Daily Active Users",
    category: "Engagement Metrics",
    definition: "The number of unique users who engage with your product on a given day. The primary pulse metric for consumer apps. A 'user' is typically defined by your team — it could mean login, a specific action, or any session.",
    formula: "Count of unique users who performed a qualifying action in a 24-hour window",
    example: "Facebook reported 2.1B DAU in Q4 2023. If DAU drops 20% overnight, that's a P0 incident requiring immediate metric diagnosis.",
    relatedTerms: ["MAU", "DAU/MAU Ratio", "Stickiness"],
    usedIn: ["Metrics & Diagnosis", "Product Improvement"],
  },
  {
    id: "mau",
    term: "MAU",
    fullName: "Monthly Active Users",
    category: "Engagement Metrics",
    definition: "The number of unique users who engage with your product at least once in a 30-day window. Used to measure the total addressable active base and to calculate stickiness alongside DAU.",
    formula: "Count of unique users who performed a qualifying action in a 30-day rolling window",
    example: "Spotify reports MAU as its headline growth metric. A product with 10M MAU but 1M DAU has a stickiness problem.",
    relatedTerms: ["DAU", "DAU/MAU Ratio", "WAU"],
    usedIn: ["Metrics & Diagnosis", "Growth"],
  },
  {
    id: "wau",
    term: "WAU",
    fullName: "Weekly Active Users",
    category: "Engagement Metrics",
    definition: "Unique users active within a 7-day window. Most useful for products with a natural weekly usage cadence — productivity tools, B2B SaaS, or news apps — where daily is too granular and monthly is too broad.",
    formula: "Count of unique users who performed a qualifying action in a 7-day rolling window",
    example: "Slack measures WAU because work happens on weekdays. A drop in WAU on a Monday can signal a weekend outage or a competitor launch.",
    relatedTerms: ["DAU", "MAU"],
    usedIn: ["Metrics & Diagnosis"],
  },
  {
    id: "dau-mau",
    term: "DAU/MAU",
    fullName: "DAU/MAU Ratio (Stickiness)",
    category: "Engagement Metrics",
    definition: "The ratio of daily to monthly active users, expressing how often your monthly users return daily. A proxy for habit formation and product stickiness. Higher is better — 50%+ is considered excellent for consumer apps.",
    formula: "DAU ÷ MAU × 100%",
    example: "Facebook historically had ~65% DAU/MAU, meaning most monthly users came back every day. A social app at 10% DAU/MAU has a serious retention problem.",
    relatedTerms: ["DAU", "MAU", "Retention"],
    usedIn: ["Metrics & Diagnosis", "Product Improvement"],
  },
  {
    id: "retention",
    term: "Retention Rate",
    fullName: "User Retention Rate",
    category: "Engagement Metrics",
    definition: "The percentage of users who return to your product after their first visit, measured at a specific time interval (Day 1, Day 7, Day 30). The single most important signal of product-market fit. Flat retention curves indicate a sustainable product.",
    formula: "Users active in period N who were also active in period 0 ÷ Total users in period 0 × 100%",
    example: "If 1,000 users sign up in January and 300 are still active in February, your Month-1 retention is 30%. World-class mobile games target D1 > 40%, D7 > 20%, D30 > 10%.",
    relatedTerms: ["Churn Rate", "DAU/MAU", "LTV"],
    usedIn: ["Metrics & Diagnosis", "Product Improvement", "Growth"],
  },
  {
    id: "churn",
    term: "Churn Rate",
    fullName: "Customer Churn Rate",
    category: "Engagement Metrics",
    definition: "The percentage of users or customers who stop using your product in a given period. The inverse of retention. For subscription businesses, churn directly erodes MRR. Even small improvements in churn have outsized LTV impact.",
    formula: "Users lost in period ÷ Users at start of period × 100%",
    example: "A SaaS product with 5% monthly churn loses ~46% of its customer base annually. Reducing churn from 5% to 3% can double LTV.",
    relatedTerms: ["Retention Rate", "LTV", "MRR"],
    usedIn: ["Metrics & Diagnosis", "Product Improvement"],
  },
  {
    id: "session-length",
    term: "Session Length",
    fullName: "Average Session Duration",
    category: "Engagement Metrics",
    definition: "The average amount of time a user spends in a single app session. Context-dependent: longer is better for entertainment (Netflix, YouTube), shorter is better for utility apps (banking, maps) where efficiency is the goal.",
    formula: "Total time spent across all sessions ÷ Total number of sessions",
    example: "TikTok's average session length is ~10 minutes. A banking app with 10-minute sessions likely has a UX problem — users can't find what they need.",
    relatedTerms: ["DAU", "Engagement Rate"],
    usedIn: ["Metrics & Diagnosis", "Product Improvement"],
  },
  {
    id: "engagement-rate",
    term: "Engagement Rate",
    fullName: "Feature / Content Engagement Rate",
    category: "Engagement Metrics",
    definition: "The percentage of users who interact with a specific feature, content item, or call-to-action out of those who were exposed to it. Used to evaluate feature adoption and content performance.",
    formula: "Users who engaged ÷ Users who were exposed × 100%",
    example: "If 10,000 users see a new 'Share' button and 800 click it, the engagement rate is 8%. Benchmarks vary widely by feature type.",
    relatedTerms: ["CTR", "Adoption Rate"],
    usedIn: ["Metrics & Diagnosis", "Product Improvement"],
  },
  {
    id: "ctr",
    term: "CTR",
    fullName: "Click-Through Rate",
    category: "Engagement Metrics",
    definition: "The percentage of users who click on a link, button, or ad out of the total who saw it. A key signal for content relevance, notification effectiveness, and ad performance.",
    formula: "Clicks ÷ Impressions × 100%",
    example: "A push notification with 2% CTR is considered strong. Email CTR benchmarks are typically 2–5% across industries.",
    relatedTerms: ["Engagement Rate", "Conversion Rate"],
    usedIn: ["Metrics & Diagnosis", "Growth"],
  },

  // ── Growth & Acquisition ─────────────────────────────────────────────
  {
    id: "cac",
    term: "CAC",
    fullName: "Customer Acquisition Cost",
    category: "Growth & Acquisition",
    definition: "The total cost to acquire one new paying customer, including marketing spend, sales salaries, and overhead. The central cost metric in growth. Must always be evaluated against LTV — a healthy business has LTV:CAC > 3:1.",
    formula: "Total acquisition spend ÷ Number of new customers acquired",
    example: "If you spend $100K on ads and acquire 1,000 customers, CAC = $100. If your LTV is $150, you're barely profitable. If LTV is $500, you have a strong growth engine.",
    relatedTerms: ["LTV", "LTV:CAC Ratio", "ROAS"],
    usedIn: ["Growth", "Product Strategy", "Monetization"],
  },
  {
    id: "ltv",
    term: "LTV",
    fullName: "Customer Lifetime Value",
    category: "Growth & Acquisition",
    definition: "The total revenue a business expects to earn from a customer over the entire duration of their relationship. The central revenue metric in growth. Often calculated as ARPU × average customer lifespan, or ARPU ÷ Churn Rate.",
    formula: "ARPU ÷ Churn Rate  OR  ARPU × Average Customer Lifespan",
    example: "A SaaS product with $50/month ARPU and 2% monthly churn has LTV = $50 ÷ 0.02 = $2,500. With CAC of $500, LTV:CAC = 5:1 — a healthy ratio.",
    relatedTerms: ["CAC", "ARPU", "Churn Rate", "LTV:CAC Ratio"],
    usedIn: ["Growth", "Monetization", "Product Strategy"],
  },
  {
    id: "ltv-cac",
    term: "LTV:CAC",
    fullName: "Lifetime Value to Customer Acquisition Cost Ratio",
    category: "Growth & Acquisition",
    definition: "The ratio of customer lifetime value to acquisition cost. The fundamental unit economics health check. < 1:1 means you lose money on every customer. 1–3:1 is marginal. > 3:1 is healthy. > 5:1 may indicate underinvestment in growth.",
    formula: "LTV ÷ CAC",
    example: "Benchmark: SaaS companies target LTV:CAC > 3:1. If your ratio is 1.5:1, you need to either reduce CAC (better targeting) or increase LTV (reduce churn, upsell).",
    relatedTerms: ["LTV", "CAC"],
    usedIn: ["Growth", "Product Strategy", "Monetization"],
  },
  {
    id: "viral-coefficient",
    term: "K-Factor",
    fullName: "Viral Coefficient (K-Factor)",
    category: "Growth & Acquisition",
    definition: "The average number of new users each existing user brings in. A K-factor > 1 means the product grows exponentially without paid acquisition. Even a K-factor of 0.5 meaningfully reduces effective CAC.",
    formula: "Average invites sent per user × Conversion rate of those invites",
    example: "If each user invites 5 friends and 20% sign up, K = 5 × 0.2 = 1.0. Dropbox's referral program achieved K > 1, enabling viral growth.",
    relatedTerms: ["CAC", "NUX", "Referral Rate"],
    usedIn: ["Growth", "Product Design"],
  },
  {
    id: "conversion-rate",
    term: "Conversion Rate",
    fullName: "Funnel Conversion Rate",
    category: "Growth & Acquisition",
    definition: "The percentage of users who complete a desired action — signing up, purchasing, upgrading — out of those who entered the funnel. Measured at each funnel stage to identify drop-off points.",
    formula: "Users who completed action ÷ Users who started the funnel × 100%",
    example: "If 10,000 users visit your pricing page and 500 subscribe, conversion rate = 5%. Improving this from 5% to 6% is a 20% revenue increase with no additional traffic cost.",
    relatedTerms: ["CTR", "Funnel Analysis", "CAC"],
    usedIn: ["Growth", "Metrics & Diagnosis", "Product Improvement"],
  },
  {
    id: "activation-rate",
    term: "Activation Rate",
    fullName: "User Activation Rate",
    category: "Growth & Acquisition",
    definition: "The percentage of new sign-ups who reach your product's 'aha moment' — the point where they first experience core value. Activation is the bridge between acquisition and retention. Low activation = leaky top of funnel.",
    formula: "Users who hit the activation milestone ÷ Total new sign-ups × 100%",
    example: "Twitter's activation milestone was following 30 accounts. Slack's was sending 2,000 messages as a team. Improving activation from 20% to 30% can double long-term retention.",
    relatedTerms: ["Retention Rate", "NUX", "Onboarding"],
    usedIn: ["Growth", "Product Improvement", "Product Design"],
  },
  {
    id: "payback-period",
    term: "Payback Period",
    fullName: "CAC Payback Period",
    category: "Growth & Acquisition",
    definition: "The number of months it takes to recover the cost of acquiring a customer through their revenue. A shorter payback period means faster reinvestment into growth. SaaS benchmarks: < 12 months is excellent, 12–18 months is acceptable.",
    formula: "CAC ÷ Monthly ARPU (or Monthly Gross Margin per customer)",
    example: "CAC of $600 with $50/month ARPU = 12-month payback. If you raise prices to $75/month, payback drops to 8 months — freeing up capital to reinvest in growth faster.",
    relatedTerms: ["CAC", "LTV", "ARPU"],
    usedIn: ["Growth", "Monetization"],
  },

  // ── Revenue & Business ───────────────────────────────────────────────
  {
    id: "arpu",
    term: "ARPU",
    fullName: "Average Revenue Per User",
    category: "Revenue & Business",
    definition: "The average revenue generated per user (or account) in a given period. Used to track monetization efficiency and compare across segments. Can be calculated monthly (ARPU) or annually (ARPA).",
    formula: "Total Revenue ÷ Total Active Users (in the same period)",
    example: "If Spotify earns $100M from 50M premium users in a month, ARPU = $2. Comparing free vs. paid ARPU reveals the value of your premium tier.",
    relatedTerms: ["LTV", "MRR", "ARPPU"],
    usedIn: ["Monetization", "Metrics & Diagnosis"],
  },
  {
    id: "arppu",
    term: "ARPPU",
    fullName: "Average Revenue Per Paying User",
    category: "Revenue & Business",
    definition: "Like ARPU but restricted to paying users only. More relevant for freemium products where a small percentage of users generate all revenue. Helps isolate monetization health from growth metrics.",
    formula: "Total Revenue ÷ Number of Paying Users",
    example: "A mobile game with 1M users but only 50K paying users at $10/month has ARPPU = $10 and ARPU = $0.50. The gap reveals the freemium conversion challenge.",
    relatedTerms: ["ARPU", "Conversion Rate", "LTV"],
    usedIn: ["Monetization"],
  },
  {
    id: "mrr",
    term: "MRR",
    fullName: "Monthly Recurring Revenue",
    category: "Revenue & Business",
    definition: "The predictable, recurring revenue a subscription business earns each month. The primary financial health metric for SaaS. Broken into New MRR (new customers), Expansion MRR (upsells), and Churned MRR (cancellations).",
    formula: "Number of paying customers × Average monthly subscription price",
    example: "1,000 customers at $100/month = $100K MRR. If you add 50 new customers (+$5K New MRR) but lose 20 (-$2K Churned MRR), net MRR growth = +$3K.",
    relatedTerms: ["ARR", "Churn Rate", "ARPU", "NRR"],
    usedIn: ["Monetization", "Metrics & Diagnosis"],
  },
  {
    id: "arr",
    term: "ARR",
    fullName: "Annual Recurring Revenue",
    category: "Revenue & Business",
    definition: "MRR annualized. The standard top-line metric for B2B SaaS companies and the primary number used in fundraising, valuation, and board reporting. ARR = MRR × 12 (for monthly billing).",
    formula: "MRR × 12",
    example: "$100K MRR = $1.2M ARR. Enterprise SaaS companies are often valued at 5–15× ARR depending on growth rate and retention.",
    relatedTerms: ["MRR", "NRR", "Churn Rate"],
    usedIn: ["Monetization", "Product Strategy"],
  },
  {
    id: "nrr",
    term: "NRR",
    fullName: "Net Revenue Retention",
    category: "Revenue & Business",
    definition: "The percentage of revenue retained from existing customers after accounting for churn, downgrades, and expansions (upsells/cross-sells). NRR > 100% means existing customers are growing revenue even without new customer acquisition — the hallmark of a great B2B product.",
    formula: "(Starting MRR + Expansion MRR − Churned MRR − Contraction MRR) ÷ Starting MRR × 100%",
    example: "Snowflake has historically reported NRR > 130%, meaning existing customers spend 30% more each year. Benchmark: > 120% is world-class, > 100% is healthy, < 100% is a warning sign.",
    relatedTerms: ["MRR", "ARR", "Churn Rate", "LTV"],
    usedIn: ["Monetization", "Metrics & Diagnosis"],
  },
  {
    id: "gmv",
    term: "GMV",
    fullName: "Gross Merchandise Value",
    category: "Revenue & Business",
    definition: "The total value of goods or services transacted through a marketplace platform, before fees are deducted. GMV measures marketplace scale and liquidity, not the platform's own revenue. Revenue = GMV × Take Rate.",
    formula: "Total transaction value processed through the platform",
    example: "If Airbnb processes $10B in bookings and takes a 15% fee, GMV = $10B, Revenue = $1.5B. A 10% increase in GMV with the same take rate = 10% revenue growth.",
    relatedTerms: ["Take Rate", "TPV", "Revenue"],
    usedIn: ["Metrics & Diagnosis", "Product Strategy", "Monetization"],
  },
  {
    id: "take-rate",
    term: "Take Rate",
    fullName: "Platform Take Rate (Commission Rate)",
    category: "Revenue & Business",
    definition: "The percentage of GMV that a marketplace retains as revenue. Also called 'attach rate' or 'commission rate'. Increasing take rate is a key monetization lever but risks supplier/seller churn if pushed too high.",
    formula: "Revenue ÷ GMV × 100%",
    example: "Uber's take rate is ~25–30%. Etsy raised its take rate from 5% to 6.5% in 2022, causing seller backlash but increasing revenue. The tension between take rate and seller satisfaction is a classic PM strategy question.",
    relatedTerms: ["GMV", "Revenue", "Monetization"],
    usedIn: ["Monetization", "Product Strategy"],
  },
  {
    id: "gross-margin",
    term: "Gross Margin",
    fullName: "Gross Profit Margin",
    category: "Revenue & Business",
    definition: "Revenue minus the direct cost of delivering the product or service (COGS), expressed as a percentage of revenue. High gross margin means more money available for R&D, sales, and marketing. SaaS typically targets 70–80%+ gross margin.",
    formula: "(Revenue − Cost of Goods Sold) ÷ Revenue × 100%",
    example: "A SaaS company with $10M revenue and $2M in hosting/support costs has 80% gross margin. A marketplace with $10M revenue and $7M in logistics costs has 30% gross margin — very different business models.",
    relatedTerms: ["Revenue", "COGS", "Unit Economics"],
    usedIn: ["Monetization", "Product Strategy"],
  },
  {
    id: "burn-rate",
    term: "Burn Rate",
    fullName: "Monthly Cash Burn Rate",
    category: "Revenue & Business",
    definition: "The rate at which a company spends its cash reserves each month. Net burn = expenses minus revenue. Runway = cash on hand ÷ monthly net burn. Critical context for startup PMs — it shapes prioritization and risk tolerance.",
    formula: "Monthly Expenses − Monthly Revenue (Net Burn)",
    example: "A startup with $5M in the bank and $500K/month net burn has 10 months of runway. A PM at this company should be ruthless about feature prioritization — every sprint must move the needle on revenue or retention.",
    relatedTerms: ["Runway", "Unit Economics"],
    usedIn: ["Product Strategy"],
  },

  // ── Quality & Satisfaction ───────────────────────────────────────────
  {
    id: "nps",
    term: "NPS",
    fullName: "Net Promoter Score",
    category: "Quality & Satisfaction",
    definition: "A measure of customer loyalty based on a single question: 'How likely are you to recommend this product to a friend?' (0–10 scale). Promoters (9–10) minus Detractors (0–6) = NPS. Ranges from -100 to +100.",
    formula: "% Promoters (9–10) − % Detractors (0–6)",
    example: "Apple's iPhone NPS is ~72. A score above 50 is excellent. Below 0 means more detractors than promoters — a serious loyalty problem. NPS is a lagging indicator; use it alongside retention data.",
    relatedTerms: ["CSAT", "CES", "Churn Rate"],
    usedIn: ["Metrics & Diagnosis", "Product Improvement"],
  },
  {
    id: "csat",
    term: "CSAT",
    fullName: "Customer Satisfaction Score",
    category: "Quality & Satisfaction",
    definition: "A transactional satisfaction metric measured immediately after a specific interaction (support ticket, purchase, onboarding). Users rate their satisfaction 1–5 or 1–10. More granular and actionable than NPS for specific touchpoints.",
    formula: "Sum of all satisfaction scores ÷ Number of responses (expressed as % of max possible score)",
    example: "After a support interaction, 80% of users rate it 4–5 out of 5. CSAT = 80%. Benchmark: > 80% is good for support; > 90% is excellent.",
    relatedTerms: ["NPS", "CES"],
    usedIn: ["Metrics & Diagnosis", "Product Improvement"],
  },
  {
    id: "ces",
    term: "CES",
    fullName: "Customer Effort Score",
    category: "Quality & Satisfaction",
    definition: "Measures how much effort a customer had to exert to complete a task. Lower effort = higher satisfaction and retention. Particularly useful for evaluating onboarding, checkout, and support flows. Correlates strongly with churn reduction.",
    formula: "Average response to 'How easy was it to complete your task?' (1–7 scale, 7 = very easy)",
    example: "After redesigning checkout, CES improves from 4.2 to 5.8. This predicts a reduction in cart abandonment and support tickets. CES is often more predictive of loyalty than NPS for transactional products.",
    relatedTerms: ["CSAT", "NPS", "Churn Rate"],
    usedIn: ["Product Improvement", "Product Design"],
  },
  {
    id: "bug-rate",
    term: "Bug Rate / Crash Rate",
    fullName: "Application Bug / Crash Rate",
    category: "Quality & Satisfaction",
    definition: "The percentage of sessions or users that experience a bug or app crash. A critical quality signal. High crash rates directly cause churn. Industry benchmark: < 0.1% crash rate per session for mobile apps.",
    formula: "Sessions with crashes ÷ Total sessions × 100%",
    example: "If 1% of sessions crash, and your app has 1M daily sessions, that's 10,000 crashes per day. Each crash is a potential uninstall. Reducing crash rate from 1% to 0.1% can meaningfully improve D7 retention.",
    relatedTerms: ["CSAT", "Churn Rate", "Latency"],
    usedIn: ["Metrics & Diagnosis"],
  },
  {
    id: "p99-latency",
    term: "P99 Latency",
    fullName: "99th Percentile Latency",
    category: "Quality & Satisfaction",
    definition: "The response time below which 99% of requests fall. The 'worst-case' experience for most users. P99 latency matters more than average latency because slow tail latencies disproportionately affect power users and complex workflows.",
    formula: "The response time value at the 99th percentile of all measured requests",
    example: "If P99 latency is 3 seconds, 1% of users wait > 3 seconds per request. For a search product, Google's target is P99 < 200ms. High P99 latency often causes silent churn — users just stop using the feature.",
    relatedTerms: ["Bug Rate", "Uptime", "SLA"],
    usedIn: ["Metrics & Diagnosis"],
  },

  // ── Product Frameworks ───────────────────────────────────────────────
  {
    id: "pmf",
    term: "PMF",
    fullName: "Product-Market Fit",
    category: "Product Frameworks",
    definition: "The degree to which a product satisfies a strong market demand. Sean Ellis's test: if > 40% of users say they'd be 'very disappointed' if the product disappeared, you have PMF. The most critical milestone for any early-stage product.",
    formula: "Sean Ellis Test: % of users who say 'very disappointed' if product went away > 40%",
    example: "Superhuman famously used the 40% test to identify their PMF segment. Before PMF, optimize for learning. After PMF, optimize for growth. Premature scaling before PMF is the #1 startup killer.",
    relatedTerms: ["Retention Rate", "NPS", "ICP"],
    usedIn: ["Product Strategy", "Product Design"],
  },
  {
    id: "jtbd",
    term: "JTBD",
    fullName: "Jobs To Be Done",
    category: "Product Frameworks",
    definition: "A framework for understanding user motivation: people 'hire' products to do a 'job' in their life. The job is the progress the user is trying to make in a given circumstance. Focuses on context and motivation rather than demographics.",
    formula: "When [situation], I want to [motivation], so I can [outcome]",
    example: "People don't buy a drill — they hire it to make a hole. People don't buy Slack — they hire it to reduce email and feel organized. JTBD reframes product decisions around the underlying human need.",
    relatedTerms: ["User Persona", "Pain Points", "Value Proposition"],
    usedIn: ["Product Design", "Product Improvement"],
  },
  {
    id: "north-star",
    term: "North Star Metric",
    fullName: "North Star Metric (NSM)",
    category: "Product Frameworks",
    definition: "The single metric that best captures the core value your product delivers to customers. It aligns the entire team and serves as the primary long-term growth indicator. A good NSM is leading (predicts revenue), actionable, and reflects customer value.",
    formula: "Varies by product — must reflect value delivered, not just usage",
    example: "Airbnb: Nights Booked. Spotify: Time Spent Listening. Slack: Messages Sent. Facebook: DAU. The NSM is not revenue — it's the metric that, when it grows, revenue follows.",
    relatedTerms: ["DAU", "Retention Rate", "GMV"],
    usedIn: ["Metrics & Diagnosis", "Product Strategy"],
  },
  {
    id: "pirate-metrics",
    term: "AARRR",
    fullName: "Pirate Metrics (AARRR Framework)",
    category: "Product Frameworks",
    definition: "Dave McClure's framework for mapping the customer journey: Acquisition → Activation → Retention → Referral → Revenue. Each stage has its own metrics and levers. Used to diagnose where in the funnel a product is losing users.",
    formula: "Acquisition → Activation → Retention → Referral → Revenue",
    example: "If your Acquisition is strong (high traffic) but Activation is weak (low sign-up completion), the problem is onboarding, not marketing. AARRR helps you prioritize which funnel stage to fix first.",
    relatedTerms: ["Conversion Rate", "Activation Rate", "Retention Rate", "K-Factor"],
    usedIn: ["Growth", "Metrics & Diagnosis"],
  },
  {
    id: "ice",
    term: "ICE Score",
    fullName: "Impact, Confidence, Ease Score",
    category: "Product Frameworks",
    definition: "A simple prioritization framework. Each feature or initiative is scored 1–10 on Impact (how much will it move the needle?), Confidence (how sure are we?), and Ease (how easy is it to build?). ICE = (I + C + E) ÷ 3.",
    formula: "(Impact + Confidence + Ease) ÷ 3",
    example: "Feature A: Impact 8, Confidence 7, Ease 3 → ICE = 6. Feature B: Impact 5, Confidence 9, Ease 9 → ICE = 7.7. Feature B wins despite lower impact because it's fast and high-confidence.",
    relatedTerms: ["RICE Score", "MoSCoW", "Opportunity Scoring"],
    usedIn: ["Product Strategy", "Product Improvement"],
  },
  {
    id: "rice",
    term: "RICE Score",
    fullName: "Reach, Impact, Confidence, Effort Score",
    category: "Product Frameworks",
    definition: "A more rigorous prioritization framework than ICE. Reach = how many users affected per quarter. Impact = effect per user (0.25–3×). Confidence = % certainty. Effort = person-months. Higher RICE = higher priority.",
    formula: "(Reach × Impact × Confidence%) ÷ Effort",
    example: "Feature with Reach 5,000, Impact 2×, Confidence 80%, Effort 2 months → RICE = (5000 × 2 × 0.8) ÷ 2 = 4,000. Compare across features to prioritize objectively.",
    relatedTerms: ["ICE Score", "MoSCoW"],
    usedIn: ["Product Strategy", "Product Improvement"],
  },
  {
    id: "moscow",
    term: "MoSCoW",
    fullName: "Must Have, Should Have, Could Have, Won't Have",
    category: "Product Frameworks",
    definition: "A requirements prioritization method. Must Have = non-negotiable for launch. Should Have = important but not critical. Could Have = nice-to-have if time permits. Won't Have = explicitly out of scope for this release.",
    formula: "Categorize each requirement into M / S / C / W",
    example: "For a new checkout flow: Must Have = payment processing, Should Have = saved cards, Could Have = one-click checkout, Won't Have = crypto payments. MoSCoW prevents scope creep by forcing explicit trade-offs.",
    relatedTerms: ["ICE Score", "RICE Score"],
    usedIn: ["Product Design", "Product Strategy"],
  },
  {
    id: "icp",
    term: "ICP",
    fullName: "Ideal Customer Profile",
    category: "Product Frameworks",
    definition: "A detailed description of the type of company or user that gets the most value from your product and is most likely to become a loyal, high-value customer. Used to focus acquisition, product, and sales efforts on the highest-ROI segment.",
    formula: "Firmographic + behavioral + psychographic attributes of your best customers",
    example: "Slack's ICP: tech-forward companies with 50–500 employees, remote-first culture, existing Jira/GitHub users. Knowing your ICP helps you say no to features that serve non-ICP users at the expense of ICP users.",
    relatedTerms: ["PMF", "JTBD", "User Persona"],
    usedIn: ["Product Strategy", "Product Design"],
  },
  {
    id: "mvp",
    term: "MVP",
    fullName: "Minimum Viable Product",
    category: "Product Frameworks",
    definition: "The smallest version of a product that delivers enough value to attract early adopters and validate core assumptions. The goal is to learn, not to ship a polished product. An MVP tests the riskiest assumption with the least effort.",
    formula: "Minimum features needed to test the core value hypothesis",
    example: "Dropbox's MVP was a 3-minute demo video — no product existed. Airbnb's MVP was a website with photos of the founders' apartment. The question is: what is the cheapest way to test if users want this?",
    relatedTerms: ["PMF", "JTBD", "Activation Rate"],
    usedIn: ["Product Design", "Product Strategy"],
  },

  // ── Experimentation ──────────────────────────────────────────────────
  {
    id: "ab-test",
    term: "A/B Test",
    fullName: "A/B Test (Split Test)",
    category: "Experimentation",
    definition: "A controlled experiment where users are randomly split into two groups: Control (A, existing experience) and Treatment (B, new experience). Statistical significance determines if the observed difference is real or due to chance. The gold standard for product decisions.",
    formula: "Statistical significance: p-value < 0.05 (95% confidence) with sufficient sample size",
    example: "Testing a new checkout button color: 50% of users see blue (control), 50% see green (treatment). After 2 weeks with 10,000 users per group, green shows +3% conversion with p < 0.05 → ship it.",
    relatedTerms: ["Statistical Significance", "p-value", "Holdout Group"],
    usedIn: ["Metrics & Diagnosis", "Product Improvement"],
  },
  {
    id: "statistical-significance",
    term: "Statistical Significance",
    fullName: "Statistical Significance (p-value)",
    category: "Experimentation",
    definition: "A measure of confidence that an observed result is not due to random chance. In A/B testing, p < 0.05 (95% confidence) is the standard threshold. A statistically significant result means you can act on the data with confidence.",
    formula: "p-value < 0.05 = statistically significant at 95% confidence level",
    example: "Your A/B test shows Treatment B has +2% conversion. But with only 200 users per group, p = 0.3 — not significant. You need more data. With 5,000 users per group, p = 0.02 — now you can ship.",
    relatedTerms: ["A/B Test", "Sample Size", "Power Analysis"],
    usedIn: ["Metrics & Diagnosis", "Experimentation"],
  },
  {
    id: "holdout",
    term: "Holdout Group",
    fullName: "Holdout / Control Group",
    category: "Experimentation",
    definition: "A percentage of users intentionally excluded from a new feature or change to serve as a long-term baseline. Unlike A/B tests (which run for weeks), holdouts can run for months to measure long-term effects like retention impact.",
    formula: "Typically 5–10% of users held back from a new feature",
    example: "After launching a new notification system, keep 10% of users on the old system for 90 days. If the holdout group has 5% higher retention, the new notifications are hurting long-term engagement despite short-term CTR gains.",
    relatedTerms: ["A/B Test", "Retention Rate"],
    usedIn: ["Metrics & Diagnosis", "Experimentation"],
  },
  {
    id: "novelty-effect",
    term: "Novelty Effect",
    fullName: "Novelty Effect (Primacy / Recency Bias)",
    category: "Experimentation",
    definition: "The tendency for users to engage more with a new feature simply because it is new, not because it is better. A/B test results can be inflated by novelty. Mitigate by running tests long enough for novelty to wear off (typically 2–4 weeks).",
    formula: "Monitor metric trends over time — novelty-driven lifts decay; real improvements sustain",
    example: "A new homepage layout shows +15% CTR in week 1. By week 3, it's +3%. The initial spike was novelty. Ship only if the sustained lift is meaningful.",
    relatedTerms: ["A/B Test", "Statistical Significance"],
    usedIn: ["Metrics & Diagnosis", "Experimentation"],
  },
  {
    id: "guardrail-metric",
    term: "Guardrail Metric",
    fullName: "Guardrail / Counter Metric",
    category: "Experimentation",
    definition: "A metric you monitor during an experiment to ensure your primary metric improvement doesn't come at the cost of something important. If a guardrail metric degrades significantly, you stop the experiment even if the primary metric is winning.",
    formula: "Define acceptable degradation thresholds before the experiment starts",
    example: "Testing a more aggressive push notification strategy to improve DAU (primary metric). Guardrail metrics: unsubscribe rate, app uninstall rate, CSAT. If unsubscribes spike 50%, stop the test — you're burning long-term trust for short-term engagement.",
    relatedTerms: ["A/B Test", "North Star Metric"],
    usedIn: ["Metrics & Diagnosis", "Experimentation"],
  },

  // ── Infrastructure & Tech ────────────────────────────────────────────
  {
    id: "sla",
    term: "SLA",
    fullName: "Service Level Agreement",
    category: "Infrastructure & Tech",
    definition: "A formal commitment between a service provider and customer defining expected performance levels — typically uptime, response time, and support resolution time. Breaching an SLA often triggers financial penalties. Critical context for B2B PMs.",
    formula: "Uptime SLA: (Total time − Downtime) ÷ Total time × 100%",
    example: "A 99.9% uptime SLA allows 8.7 hours of downtime per year. A 99.99% ('four nines') SLA allows only 52 minutes. Enterprise customers often require four-nines SLAs, which significantly increases infrastructure investment.",
    relatedTerms: ["Uptime", "P99 Latency", "Incident Response"],
    usedIn: ["Product Strategy", "Metrics & Diagnosis"],
  },
  {
    id: "api",
    term: "API",
    fullName: "Application Programming Interface",
    category: "Infrastructure & Tech",
    definition: "A defined interface that allows different software systems to communicate. For PMs, APIs are a product surface — they enable third-party integrations, developer ecosystems, and platform strategies. An API-first strategy can turn your product into a platform.",
    formula: "N/A — conceptual",
    example: "Stripe's API is its product. Twilio's API is its product. When Slack opened its API, it enabled 2,000+ integrations that made the product stickier. A PM should understand API rate limits, versioning, and developer experience.",
    relatedTerms: ["Platform Strategy", "Webhook", "SDK"],
    usedIn: ["Product Strategy", "Product Design"],
  },
  {
    id: "technical-debt",
    term: "Technical Debt",
    fullName: "Technical Debt",
    category: "Infrastructure & Tech",
    definition: "The implied cost of future rework caused by choosing a fast, easy solution now instead of a better, slower one. Accumulates over time and slows down feature development. PMs must balance shipping speed against long-term velocity.",
    formula: "N/A — qualitative, but can be estimated as % of engineering time spent on maintenance vs. new features",
    example: "A startup ships a feature in 2 weeks using shortcuts. 18 months later, every new feature takes 3× longer because of the accumulated debt. A PM should advocate for regular 'debt sprints' to maintain engineering velocity.",
    relatedTerms: ["Velocity", "Refactoring"],
    usedIn: ["Product Strategy"],
  },
  {
    id: "latency",
    term: "Latency",
    fullName: "System Latency / Response Time",
    category: "Infrastructure & Tech",
    definition: "The time delay between a user action and the system's response. Directly impacts user experience and conversion rates. Amazon found that every 100ms of latency costs 1% in sales. Google found that a 0.5-second delay reduces search volume by 20%.",
    formula: "Time from request initiation to first byte received (TTFB) or full response",
    example: "A search feature with 2-second P50 latency feels slow. Reducing it to 200ms can increase query volume by 20–30%. Latency is especially critical for real-time features like messaging, maps, and search.",
    relatedTerms: ["P99 Latency", "SLA", "Uptime"],
    usedIn: ["Metrics & Diagnosis", "Product Improvement"],
  },
];

export const GLOSSARY_CATEGORIES = Array.from(
  new Set(glossary.map((t) => t.category))
) as GlossaryCategory[];

export const ALPHABET = Array.from(
  new Set(glossary.map((t) => t.term[0].toUpperCase()))
).sort();
